name: Feature

on:
  push:
    branches:
      - 'feature/*'

jobs:
  terraform-format:
    name: Check Terraform Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Format
        run: terraform fmt -check

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: |
          cd terraform/lambda
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform/lambda
          terraform plan

  createPullRequest:
    runs-on: ubuntu-latest
    needs: terraform-plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Merge Feature para Main"
          pr_body: "Pull request automático para main."
          pr_label: "automated-pr"
          pr_draft: true
          base: "main"
          head: "${{ github.ref }}"

  database-migration:
    name: Database Migration
    runs-on: ubuntu-latest
    needs: terraform-plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Database Migrations
        run: |
          psql -h db-fiap-burger-svc -U cG9zdGdyZXM= -d postgres -a -f database/migrations/01_create_tables.sql
        env:
          PGPASSWORD: 'MTIzNDU2'